name: "Siddharth Sharma"
description: "This is the online resume of siddharth sharma. explore to know more about me"

url: "http://localhost:4000"

paginate: 5
paginate_path: "blog/page:num"
paginate_destination: "_site/blog"

markdown: rdiscount
permalink: pretty
highlighter: pygments

